queue_rules:
  - name: default
    queue_conditions:
      - author~=^dependabot(|-preview)\[bot\]$
      - status-success=verify
      - author~=^edgedalmacio$
      - status-success=verify
      - label=ready-to-merge
    conditions:
      - status-success=verify
    merge_method: rebase

pull_request_rules:
  - name: refactored queue action rule
    conditions: []
    actions:
      queue:
