dist: trusty
language: java
install: true
addons:
  sonarcloud:
    organization: edgedalmacio-github
    token:
      secure: ba66TecEvVZ87WmZFq4PfGcjS+NLfFJ43IKWk8euA9KIcoIxC5lsjFQEsiyMDElYfs2LU2G2kzThY3p80jZGhnm2GTqSqm8qfV5OVVIQoflq/2K6+RKJ+ZSXIoZ6gWHu/kFtioIrY6zulr7TvR8u5IBuC07H25RlTz3Z+EMiaAymjLCOT2nxJSG8WHerYRP96+ID6rUH9e3MmCk8flt8ld87p2+66Dhod4HWq+heM1VUjlFuU3tXaLcQz8mHxinUu5V3qXQ0lEV3O2WbE6HqGYbsLcnbDwwQy7CUhz7K79yc3MBD0MUsPgj7RJf1edu3wgfvfsSmOiFrfcyNUE6tUCH3pDwRlJ0P9G79mKujoc9fikgKxw7t5+zlk322TMEDvM30Xy1RZGXG/auy1PKLTQCO77mjLECQfys3v5CmwflEUQleY7kkEKRuHNASgmyJwBvC+ZjlvaU5P4Ibo5RRX0T8XOBToV0bu+qEeaaT+LXed8xbhtfKvzM6CUDFvRXSeNhnmvd4PAXY7rEPJ6Jsnls7tYfqqVDvH5DqyUUY1oHyaQ7aop4yufHS33OgE4drX2rA9B9xgcCiOVUIO4ChwjDgOeMfB+7Wbd4RkZu+L+tCidYUnXfTIsnn9D4PQoMY4x+Eu75rWRv2gqJo+ULOx5qPNRkMxRBVRqpsIHrAKuc=
jdk:
- oraclejdk8
env:
  matrix:
    secure: EokAWva6gfwYCz+ljHPC1m+zrqmgtTmmym/o+QwUm7xPjJtPl1fHQyxQFPWPrnOVKGVV+9AVPY3O3UHdhyEiuvA6Pjkb6RB0Zi7vaqPyGsyxdiDiYVzkiTwdvrMWNofK/Kmdio+RVuYXb5AVQmKAAwabau+A4ZrLZhFb72ed7E4=
  global:
  - PATH=${HOME}/.cache/google-cloud-tools-java/managed-cloud-sdk/LATEST/google-cloud-sdk/bin/:${PATH}
before_install:
- openssl aes-256-cbc -K $encrypted_811413ac669a_key -iv $encrypted_811413ac669a_iv -in phisix-api-f6d7427c49af.json.enc -out phisix-api-f6d7427c49af.json -d
script:
- mvn -B clean org.jacoco:jacoco-maven-plugin:prepare-agent verify
after_success:
- ./deploy.sh
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sonar/cache"
  - "$HOME/.cache"
branches:
  only:
  - master
